name: 95等级签到

on:
  schedule:
    - cron: '22 13 * * *'  # 每天 UTC 时间 13:22 执行（北京时间 21:22）
  workflow_dispatch:  # 添加手动触发

jobs:
  run_script:
    runs-on: ubuntu-latest

    env:
      ACCOUNT: ${{ secrets.ACCOUNT }}  # 使用 GitHub Secrets 来存储敏感信息
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run login script
      run: python 95buff.py
