name: Daily Login

on:
  schedule:
    - cron: '22 13 * * *'  # 每天 UTC 时间 13:22 执行（北京时间 21:22）
  workflow_dispatch:  # 添加手动触发

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # 安装依赖并运行脚本
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run login script
      run: python 95buff.py  # 替换为你的 Python 脚本文件名
